#!/bin/bash
#set -vx # For debugging only

BASE_OUTPUT_FOLDER="$1"
VERSION="2.0.0"

if [ -z "$BASE_OUTPUT_FOLDER" ]
    then
        echo "Base output folder not provided, please provide the base output folder generated by Jovian as an argument to this script. By default: \`bash launch_report.sh ./\`"
        exit 1
fi

if [ ! -d "$BASE_OUTPUT_FOLDER" ]
    then
        echo "This is not a directory, please provide the base output folder generated by Jovian"
        exit 1
fi

if ! command -v singularity &> /dev/null
    then
        echo "Singularity could not be found. The visualisation report relies on this program, please install it on your system or ask a system-admin to do this for you. See: https://docs.sylabs.io/guides/3.0/user-guide/installation.html . Exiting."
        exit 1
fi

set -euo pipefail

cd "${BASE_OUTPUT_FOLDER}"

if [ ! -f "jovian_report_${VERSION}.sif" ]
    then
        echo "Downloading singularity container, this may take a while."
        singularity pull library://ds_bioinformatics/jovian/jovian_report:${VERSION}
fi

mkdir -p ./.nginx/tmp/nginx  ./.nginx/run/ ./.nginx/log/

singularity run --bind ./:/opt/.jupyter/migrated \
--bind ./.nginx/log:/opt/conda/var/log/nginx/ --bind ./.nginx/run:/opt/conda/var/run/ --bind ./.nginx/tmp:/opt/conda/var/tmp/ \
--bind ./results/:/opt/Jovian/results/ --bind ./data/:/opt/Jovian/data/ --bind ./logs/:/opt/Jovian/logs/ \
jovian_report_${VERSION}.sif
